### PR TITLE
Package rebuild

### PR DESCRIPTION
**Pull request by sameeul**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by sameeul** [comment]
@conda-forge-admin, please rerender

**Comment by sameeul** [comment]
This produces a new pypubsub build with updated compatibility tag. @constantinpape , could you please have a look?
We needed this for the packages to be compatible with pip >=24.2

For reference, we had to do the same here: https://github.com/conda-forge/untokenize-feedstock/pull/3

**Comment by zklaus** [comment]
@conda-forge-admin, please rerender

**Comment by zklaus** [comment]
Thanks for picking this up, @sameeul! The issue seems to be that the rerendering didn't update the permissions for some scripts correctly. I have opened a PR that targets your branch at https://github.com/sameeul/pypubsub-feedstock/pull/1.

**Comment by constantinpape** [comment]
Hi @sameeul ,
I am not sure how this is related to any of my libraries. Could you expand on this?

**Comment by sameeul** [comment]
@constantinpape : You are actually listed as a recipe-maintainer for this feedstock. I do not think this has any relation with any other libraries that you maintain :-)

**Pull request merged**
